CREATE DATABASE IF NOT EXISTS raw_criteria;
CREATE DATABASE IF NOT EXISTS raw_insights;
CREATE DATABASE IF NOT EXISTS raw_report;
CREATE DATABASE IF NOT EXISTS raw_encounters;
CREATE DATABASE IF NOT EXISTS raw_gdb;
CREATE DATABASE IF NOT EXISTS prod;
CREATE DATABASE IF NOT EXISTS stage;