- name: Clone Git repositories
  hosts: localhost
  tasks:
    - name: Clone ds-reporting-logic
      git:
        repo: 'ssh://git@bitbucket.collectivemedicaltech.com:7999/dh/ds-reporting-logic.git'
        dest: '../ds-reporting-logic'
    - name: Clone ds-reporting-scheduling
      git:
        repo: 'ssh://git@bitbucket.collectivemedicaltech.com:7999/dh/ds-reporting-scheduling.git'
        dest: '../ds-reporting-scheduling'