all:
  children:
    control-node:
      hosts:
        dc2-ds-etl-01.int.collectivemedicaltech.com:
          ansible_host: 192.168.53.194
          ansible_user: marc.keeling
          node_number: 1
          ssl_cert_common_name: "clickhouse_etl"

    satellite-nodes:
      hosts:
        dc2-ds-db-01.int.collectivemedicaltech.com:
          ansible_host: 192.168.53.196
          ansible_user: marc.keeling
          node_number: 2
          ssl_cert_common_name: "clickhouse_db"

        dc2-ds-analysis-01.int.collectivemedicaltech.com:
          ansible_host: 192.168.53.195
          ansible_user: marc.keeling
          node_number: 3
          ssl_cert_common_name: "clickhouse_analysis"

    localhost:
      hosts:
        localhost:
          ansible_connection: local
