my_dbt_project:
  target: staging
  outputs:    
    staging:
      type: duckdb
      path: stage_dbt_warehouse.duckdb
      schema: main
      threads: 1
    prod:
      type: duckdb
      path: stage_dbt_warehouse.duckdb
      schema: main
      threads: 1
    dev:
      type: duckdb
      path: stage_dbt_warehouse.duckdb
      schema: charles.z
      threads: 1