version: 2

# The sources needed to create each dbt model. In this case we are using parquet files
sources:
 - name: extracts
   tables:
     - name: facility
     - name: comprehensive_encounter
     - name: ce_visit_map
    