docker_images:
  - "alpine/socat:latest"
  - "airbyte/worker:0.63.13"
  - "airbyte/webapp:0.63.13"
  - "airbyte/temporal:0.63.13"
  - "airbyte/server:0.63.13"
  - "airbyte/proxy:0.63.13"
  - "airbyte/db:0.63.13"
  - "airbyte/connector-builder-server:0.63.13"
  - "airbyte/cron:0.63.13"
  - "airbyte/init:0.63.13"
  - "airbyte/bootloader:0.63.13"

remote_path: "/tmp"
remote_server: "dc2-ds-db-01.int.collectivemedicaltech.com"