---  
- name: Ping server
  hosts: all
  tasks:
    - name: Ping the server
      ping:
    
    - name: Ensure the file exists
      file:
        path: "{{ lookup('env', 'HOME') }}/myfile.txt"
        state: touch

    - name: Confirm the file creation
      stat:
        path: "{{ lookup('env', 'HOME') }}/myfile.txt"
      register: file_stat

    - name: Print confirmation message
      debug:
        msg: "File 'myfile.txt' created successfully in the home directory."
      when: file_stat.stat.exists