# This is the main project settings file
name: "dbt_project"
version: "1.0.0"
config-version: 2

# Profile to use, can be switched like prod/dev
profile: "dbt_project"

analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# On run load parquet files into duckdb
# on-run-start: "{{ create_external_tables(this) }}"
# # After run create parquet files from new models
# on-run-end: "{{ export_tables_to_parquet(this) }}"

models:
  dbt_project:
  # Make all staging models tables, by default is a view
    cleaned:
      +materialized: table
    intermediate:
      +materialized: table
    marts:
      +materialized: table
