name: "dbt_project"
version: "1.0.0"
config-version: 2

profile: "dbt_project"

analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start: "{{ create_external_tables(this) }}"
on-run-end: "{{ export_tables_to_parquet(this) }}"

models:
  dbt_project:
    staging:
      +materialized: table
  # intermediate:
  #   +materialized: table
  # marts:
  #   +materialized: table

