all:
  hosts:
    control-node:
      ansible_host: 10.0.0.3
      ip: 10.0.0.3
      access_ip: 10.0.0.3
    server1:
      ansible_host: 10.0.0.4
      ip: 10.0.0.4
      access_ip: 10.0.0.4
    server2:
      ansible_host: 10.0.0.5
      ip: 10.0.0.5
      access_ip: 10.0.0.5
    server3:
      ansible_host: 10.0.0.6
      ip: 10.0.0.6
      access_ip: 10.0.0.6
  children:
    kube_control_plane:
      hosts:
        control-node:
        server2:
    kube_node:
      hosts:
        control-node:
        server1:
        server2:
        server3:
    etcd:
      hosts:
        control-node:
        server1:
        server2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
